name: Notify on Tag Creation

on:
  create:
    tags:
      - '*'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Check if tag is created from a branch other than master
        id: check_branch
        run: |
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            branch="${{ github.ref }}"
            echo "Branch: $branch"
            if [[ "${{ github.ref }}" != "refs/heads/master" ]]; then
              echo "Tag created from a branch other than master."
              echo "::set-output name=notify::true"
            else
              echo "Tag created from master."
              echo "::set-output name=notify::false"
            fi
          fi

      - name: Send Notification
        if: steps.check_branch.outputs.notify == 'true'
        run: |
          curl -X POST -H 'Content-type: application/json' --data '{"text":"A new tag has been created from a branch other than master: '${{ github.ref }}'"}' ${{ secrets.SLACK_WEBHOOK_URL }}
